appName = "Example Application"
version = "1.5.2"
production = false
maxUsers = 1000
price = 49.99
nullValue = null

tags = ["productivity", "utility", "v1.5"]

[metadata]
created = "2023-10-15T08:23:12Z"
modified = "2024-02-20T15:42:07Z"

[dependencies]
core = "^4.2.0"

[dependencies.auth-module]
version = "2.1.3"
optional = true

[[features]]
name = "dark-mode"
enabled = true

[features.settings]
default = "system"
options = ["light", "dark", "system"]

[[features]]
name = "notifications"
enabled = false

[colors]
primary = "#4a6bff"
secondary = "#f0a92d"